### ISSUE TITLE
Linux: undefined: api.SQL_SS_TIME2

### ISSUE THREAD

**Issue by MarkSonghurst** [alexbrainman/odbc#103]
Hi
I get a build failure with master on Linux:
```
vendor/github.com/alexbrainman/odbc/column.go:86:26: undefined: api.SQL_SS_TIME2
```
I think commit 766c1869 for api/api_windows.go needs to be duplicated in api/api_unix.go
```
SQL_SS_TIME2        = -154
```

I'd offer a PR, but I'm unsure of the implications of using -154 on Linux (I suspect it's unsupported like the XML type).

**Comment by alexbrainman** [comment]
Your suggestion sounds reasonable. Even if it is unsupported on Linux, that will make your code build. That bit of code will not run on Linux.

I will try and fix this when I am free.

Sorry for breaking your code.

Alex

**Comment by alexbrainman** [comment]
@MarkSonghurst please reopen this issue, if it still broken for you.

Alex

**Comment by MarkSonghurst** [comment]
The pacakge builds on Linux, thank you.
