### ISSUE TITLE
Adding support for stored procedures with output parameters

### ISSUE THREAD

**Issue by markotikvic** [alexbrainman/odbc#110]
Are there plans for doing this in the near future?  
Or do you have any idea how would one go about implementing this?   

Thanks.

**Comment by alexbrainman** [comment]
You would have to explain what exactly your problem is.

If you search the source for TestMSSQLExecStoredProcedure, you can see how to call MS SQL Server stored procedure with existing code. Is that not enough?

Thank you.

Alex

**Comment by markotikvic** [comment]
It looks like that's what I'm looking for. Thanks.  

The documentation does not cover the topic and I don't have time to go over source code of every package I intend to use.

**Comment by markotikvic** [comment]
I just got around to this. My question was about calling stored procedures with OUTPUT parameter(s).

Sybase: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36272.1550/html/commands/X30305.htm (under *output*)

Go: https://golang.org/pkg/database/sql/#Out

I'm just curious if this is in the plans for the future.  
Calling regular procedures works as expected.  

Thanks.

Marko

**Comment by alexbrainman** [comment]
> Go: https://golang.org/pkg/database/sql/#Out

I do not use this facility myself. So I have no plan spending my time to implement this.

If you need this, you would have to do it yourself. I am happy to help with whatever does not take much of my time. Sorry.

Alex

**Comment by markotikvic** [comment]
OK. If I get around to it I'll ask you in case I get stuck.

Thanks.

**Comment by rajesh625** [comment]
I am using DB2 with Output parameters in addition to multiple result sets. The IBM DB2 golang driver does not support multiple resultsets currently nor output parameters.
Only thing am missing here is output parameters.
I can look into changing this to add output parameters. Would it be possible for you to point me to what needs to change before i start looking at the code?
Any help is greatly appreciated.
Thank you.
