### ISSUE TITLE
Cannot open .accdb file in Ubuntu

### ISSUE THREAD

**Issue by sfmarques** [alexbrainman/odbc#123]
Hello,

I follow the install in wiki and cannot open a access file to query. Is it possible to do it in Linux?

go version go1.10.1 linux/amd64 

Thanks

**Comment by alexbrainman** [comment]
> I follow the install in wiki and cannot open a access file to query. Is it possible to do it in Linux?

I doubt. This package uses locally installed ODBC driver to access database. Do you have Access ODBC driver installed on your system?

Alex

**Comment by sfmarques** [comment]
Sorry, no. Isto there a free Access ODBC driver for Linux?

**Comment by alexbrainman** [comment]
I do not know of any Access ODBC driver for Linux.

Alex
