### ISSUE TITLE
SQLDriverConnect: with MSAccess if not db.SetMaxIdleConns(0)

### ISSUE THREAD

**Issue by flibustenet** [alexbrainman/odbc#125]
On one system I had this randomly error `SQLDriverConnect:` without any detail.
Trying to reinstall odbc driver, doesn't change.
The workaround was to prevent db connection pooling db.SetMaxIdleConns(0)

Don't know if it's worse investigating or just use this workaround... (still strange that the error is not more verbose)
On other systems I didn't see this error.

I added a wiki page with my adventure with MSAccess
https://github.com/alexbrainman/odbc/wiki/Tips-for-MSAccess

**Comment by alexbrainman** [comment]
> On one system I had this randomly error `SQLDriverConnect:` without any detail.

That is not enough information for me to investigate.

> The workaround was to prevent db connection pooling db.SetMaxIdleConns(0)

If that works, use it. :-)

> I added a wiki page with my adventure with MSAccess
> https://github.com/alexbrainman/odbc/wiki/Tips-for-MSAccess

Looks good. Thank you very much. I just suggested fir for #106 so maybe you could remove mention of #106 from the wiki. Once you are happy that fix works.

Alex

**Comment by flibustenet** [comment]
Finally doesn't works... But just on one VM, could'nt find why as it's a random error. Maybe the OS.
Gave back and tried with mattn/go-adodb.
Sorry to disturb you with this dinosaur database
