### ISSUE TITLE
Can't create unixODBC trace log

### ISSUE THREAD

**Issue by gamgyul** [alexbrainman/odbc#140]
I try sample connection test and it works successfully .But UnixODBC trace file is not created.

When I run isql or sample C code using UnixODBC,  trace file is successfully created.
I checked odbcinst.ini file and changed log directory umask to 777 but still not creating trace file.
Have you experienced this? 
I try sample connection test and it succeed.
thank you in advance for your help

**Comment by alexbrainman** [comment]
> I checked odbcinst.ini file and changed log directory umask to 777 but still not creating trace file.
> Have you experienced this?

I have never needed the trace file. I do not even know it exists. I do not know how to switch it on. You should try and ask on some UnixODBC forums.

Sorry.

Alex

**Comment by gamgyul** [comment]
Ok I'll close issue.
Thank you.
