### ISSUE TITLE
Removal of --with-unixodbc flag on the brew command

### ISSUE THREAD

**Issue by ledor473** [alexbrainman/odbc#146]
I've tried to install this project on macOS but found that the `brew` command documented [here](https://github.com/alexbrainman/odbc/wiki/InstallingUnixODBCOnOSX) needed an update.

I clicked on `Edit` in the Wiki page thinking it would send a PR but turns out it was [automatically applied]( https://github.com/alexbrainman/odbc/wiki/InstallingUnixODBCOnOSX/_history) so I figured I'd file an Issue to document it.

Here's what makes me think it's not needed anymore:
https://github.com/Homebrew/homebrew-core/issues/36939#issuecomment-463854917

**Comment by alexbrainman** [comment]
> I clicked on `Edit` in the Wiki page thinking it would send a PR but turns out it was [automatically applied](https://github.com/alexbrainman/odbc/wiki/InstallingUnixODBCOnOSX/_history) so I figured I'd file an Issue to document it.

Yes. That is how Github Wiki normally works.

And thank you for adjusting the documentation. I, obviously, don't look at the documentation myself. And Darwin Wiki was written by another user, just like yourself. I don't have Mac myself, so I would not even know what the correct instructions are.

I will close this issue. Let me know, if you disagree, and there is something else to do here.

Alex
