### ISSUE TITLE
signal 13 received but handler not on signal stack

### ISSUE THREAD

**Issue by achettyiitr** [alexbrainman/odbc#167]
signal 13 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

**Comment by achettyiitr** [comment]
We are continuously getting this issue.

**Comment by alexbrainman** [comment]
@achettyiitr I don't debug someone else's programs.

Alex

**Comment by achettyiitr** [comment]
Great.

**Comment by achettyiitr** [comment]
Thanks for the update.
