### ISSUE TITLE
Low max message length

### ISSUE THREAD

**Issue by vegarsti** [alexbrainman/odbc#169]
Is it possible at all to increase the max message length? It seems to be set to 512. This is probably a constant that corresponds to a length cap in the underlying unixodbc code?

https://github.com/alexbrainman/odbc/blob/9c9a2e61c5e2c1a257a51ea49169fc9008c51f0e/api/api_unix.go#L46

I'm experiencing truncated error messages for almost all errors.

**Comment by vegarsti** [comment]
I opened an issue upstream in unixodbc: https://github.com/lurcher/unixODBC/issues/92

**Comment by alexbrainman** [comment]
> I opened an issue upstream in unixodbc: [lurcher/unixODBC#92](https://github.com/lurcher/unixODBC/issues/92)

I will wait to see what happens with the upstream issue before doing anything else here.

@vegarsti let me know if you disagree.

Thank you.

Alex

**Comment by vegarsti** [comment]
Perfect!

Since this is fully inherited from the underlying library, I don't think any change is needed here, so feel free to close this!
