### ISSUE TITLE
error when build from linux

### ISSUE THREAD

**Issue by revoluta** [alexbrainman/odbc#176]
Hello, when i build from linux i get this error:

/root/go/pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20211220213544-9c9a2e61c5e2/api/api_unix.go:15:18: fatal error: sql.h: No such file or directory

this is build from a docker container, could it be that I am missing a package?

**Comment by revoluta** [comment]
I have found the problem, I answer myself in case it helps someone:

I was missing in the docker base image the one that compiles the project to include the obdc

`RUN yum -y install unixODBC unixODBC-devel`

**Comment by alexbrainman** [comment]
@revoluta 

Should you close this issue?

Alex
