### ISSUE TITLE
The package is returning a panic instead of an error

### ISSUE THREAD

**Issue by ashwinipatankar** [alexbrainman/odbc#184]
OS: Windows
Go version: 1.16
Database: bbj

Recently, in a peculiar case the package returned a panic instead of an error. Here is the stack trace - 
`
syscall.Syscall9(0x70d5dc30, 0x8, 0x3, 0x159c788, 0x1, 0x12ccb774, 0x12ccb760, 0x12ccb780, 0x200, 0x0, ...)
        /usr/lib/go-1.16/src/runtime/syscall_windows.go:356 +0xbb
github.com/alexbrainman/odbc/api.SQLGetDiagRec(0x8b0003, 0x159c788, 0x1590001, 0x12ccb774, 0x12ccb760, 0x12ccb780, 0x200
, 0x0, 0x0)
        /home/xyz/go/pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20211220213544-9c9a2e61c5e2/api/zapi_windows.go:144 +
0xca
github.com/alexbrainman/odbc.NewError(0x92ad1b, 0xa, 0x891860, 0x12c19990, 0x352, 0x352)
github.com/alexbrainman/odbc.(*Conn).PrepareODBCStmt(0x12c04e00, 0x12d0ca80, 0x351, 0x0, 0x0, 0x0)

github.com/alexbrainman/odbc.(*Conn).Prepare(0x12c04e00, 0x12d0ca80, 0x351, 0x0, 0x0, 0x0, 0x408c7a)`

Ideally it shall return an error instead of the panic, is that correct ?

And how this can be handled ?

**Comment by alexbrainman** [comment]
> Here is the stack trace -

That is incomplete stack trace. You skipped the error message at the top of the stack trace. Also you did not provide source path and line numbers for `github.com/alexbrainman/odbc.NewError` and others.

It is impossible to suggest anything here.

Alex

**Comment by ashwinipatankar** [comment]
the complete stack trace is attached here.
[stactrace.txt](https://github.com/alexbrainman/odbc/files/10681459/stactrace.txt)

**Comment by alexbrainman** [comment]
@ashwinipatankar 

Does https://github.com/alexbrainman/odbc/pull/189 fixes your issue?

Please test. Thank you.

Alex

**Comment by alexbrainman** [comment]
@ashwinipatankar 

I expect this commit https://github.com/alexbrainman/odbc/commit/1421b829acc9091991ee8e7065fc1dfb3f885d94 fixes your problem. So I am closing the issue.

Please, reopen if you disagee.

Alex
