### ISSUE TITLE
Error : unrecognized import path "golang.zx2c4.com/go118/netip"

### ISSUE THREAD

**Issue by jiee-altibase** [alexbrainman/odbc#193]
I am developing altibase input plugin for telegraf.
altibase is an rdbms similar to oracle.
I forked telegraf 2-3 months ago.
Afterwards, I successfully tested it by linking it to the altibase odbc driver using your odbc.
However, when I download and build the latest telegraf source, an error occurs.

$ make build
CGO_ENABLED=1 go build -tags "" -ldflags " -X github.com/influxdata/telegraf/internal.Commit=66bd72be -X github.com/influxdata/telegraf/internal.Branch=HEAD -X github.com/influxdata/ telegraf/internal.Version=1.30.0-66bd72be" ./cmd/telegraf
plugins/inputs/altibase/altibase.go:11:2: golang.zx2c4.com/wireguard@v0.0.0-20211209221555-9c9e7e272434 requires
         golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go- get=1: 404 Not Found

$ go version
go version go1.22.0 linux/amd64
$ git version
git version 2.44.0
$ gcc -v
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
$ getconf -a |grep glibc
GNU_LIBC_VERSION                   glibc 2.17
$ odbc_config --version
2.3.2

There is no problem when importing your odbc from the simple sample.

package main

import (
         "fmt"
         _ "github.com/alexbrainman/odbc"
)

func main() {
     fmt.Println("Hello, Go!")
}

However, an error occurs when importing from telegraf.

Do you know the cause and solution to the error?

**Comment by alexbrainman** [comment]
> golang.zx2c4.com/go118/[netip@v0.0.0-20211111135330-a4a02eeacf9d](mailto:netip@v0.0.0-20211111135330-a4a02eeacf9d): unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go- get=1: 404 Not Found

Why does your go command receives 404 when it downloads packages?

Perhaps your go proxy is not configured or broken.

Alex

**Comment by jiee-altibase** [comment]
Thanks for the quick reply

your answer was very helpful

I changed the GOPROXY value and the build was successful.

Thank you very much
