### ISSUE TITLE
Can't query for binary blob data in informix

### ISSUE THREAD

**Issue by gxb5443** [alexbrainman/odbc#204]
I'm using odbc library with unixODBC to access informix. I have a table with a binary blob column. When I try to query for it I get an error when making the query, `unsupported column type -102`. Does the ODBC driver not support binary blobs?

**Comment by alexbrainman** [comment]
> Does the ODBC driver not support binary blobs?

I used this package with MS SQL Server. It supports binary blobs with MS SQL Server.

I never used Informix. So I would not know.

Alex

**Comment by gxb5443** [comment]
Ah I figured it out. Just to close the loop on this, your odbc library works like champ. Looks like the informix driver doesn't send standard ODBC types. You need to tell it to do so by adding "NeedODBCTypesOnly=1" to the connection string. Thanks a lot!
