### ISSUE TITLE
having a fatal error when I build a project.

### ISSUE THREAD

**Issue by RingXu999** [alexbrainman/odbc#72]
# github.com/alexbrainman/odbc/api
../../Projects/Go/src/github.com/alexbrainman/odbc/api/api_unix.go:13:11: fatal error: 'sql.h' file not found
 #include <sql.h>
          ^
1 error generated

hello. I am building a projects in OS X 10.11.3  and the above error arise.

seems like the go projects can't find the unixodbc/2.3.4/include/sql.h

but I can find it in the finder . do i miss some configure ?

i have already install the unixodbc in homebrew and install FreeTDS myself.

this problem is driving me crazy and I have no idea how to figure it out . >_<~.

**Comment by RingXu999** [comment]
i think know what leads this problem.

because the api_unix code go to the /opt/local/include to find the header files 

and my unixodbc setup in /usr/local path . then i copy the unixodbc files to the opt path and the

problem solved.  so lucky haha. Apology for my thoughtless~ ^ ^

**Comment by alexbrainman** [comment]
> Apology for my thoughtless

No worries.

Alex

**Comment by MarkSonghurst** [comment]
@alexbrainman 
FYI for Centos 7 users - to "go get" the odbc package without the sql.h error occurring, as a prerequisite you will need the unixODBC-devel RPM installed, who's version must match the unixODBC RPM (yum takes care of this.) 
Might be worth mentioning this on https://github.com/alexbrainman/odbc/wiki/InstallingUnixODBC

**Comment by alexbrainman** [comment]
> edit: I updated the wiki page, specifically the Fedora section (it's the same as Centos) - hope you don't mind :-)

I don't mind you changing wiki. I don't use these systems myself, so help from real user always appreciated. Thank you very much.

Alex
