### ISSUE TITLE
Why not treat error code of 08007 and HY000  as ErrBadConn?

### ISSUE THREAD

**Issue by lwmonster** [alexbrainman/odbc#86]
In function NewError, we treat the ODBC error code "08S01" as ErrBadConn, but in HP Vertica, if the connection is bad it will return  08007 or HY000, can we add these two to the following code?
`if r.State == "08S01" {
    return driver.ErrBadConn
}
`

**Comment by lwmonster** [comment]
Actually, when use ODBC on vertica, if a connection is closed by vertica server,  the golang sql package can't  RECONNECT, because it doesn't received a ErrBadConn error.

**Comment by alexbrainman** [comment]
> in HP Vertica, if the connection is bad it will return 08007 or HY000

Do you have any reference or documentation for that?

> can we add these two to the following code?

Sure. If you can provide some reference.

Thank you

Alex

**Comment by lwmonster** [comment]
It seems the Vertica ODBC driver is not standard, it return HY000 at many circumstances including CONNECTION error and other situation.  So, let it go...

**Comment by alexbrainman** [comment]
> So, let it go...

No problem with me.
Please, reopen if you think we can do more here.

Alex
